name: قیمت تتر هر ۳ دقیقه

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:          # برای تست دستی

jobs:
  send-price:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: نصب کتابخانه‌ها
        run: |
          python -m pip install --upgrade pip
          pip install requests python-telegram-bot jdatetime

      - name: اجرای اسکریپت
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
